# Generated by Django 5.1.2 on 2024-10-20 15:24

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="bio",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="date_of_birth",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="hobby",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="phone",
        ),
    ]
