# Generated by Django 3.2.13 on 2022-08-13 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='coach',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='editor',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='helper',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='leider',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='player',
        ),
    ]
