# Generated by Django 3.2.13 on 2022-11-11 20:24

import accounts.model.profile
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220813_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profiel',
            field=models.ImageField(default='profile/default_image.jpg', upload_to=accounts.model.profile.profile_image, verbose_name='Profiel'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='profile/default_avatar.jpg', upload_to=accounts.model.profile.profile_avatar, verbose_name='Avatar'),
        ),
    ]
