# Generated by Django 3.2.13 on 2023-08-15 13:52

import club.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(verbose_name='End Date')),
            ],
        ),
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('short_description', models.TextField(blank=True, max_length=20, null=True, verbose_name='Short description')),
                ('logo', models.ImageField(default='sponsor/default.jpg', upload_to=club.models.sponsor_logo, verbose_name='Logo')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_num', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Lid Nummer')),
                ('fee', models.FloatField(verbose_name='Cost')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.season', verbose_name='Season')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Title -> 1x naam perdag, Verander naam hier != als file naam')),
                ('description', models.TextField(blank=True, max_length=30, null=True, verbose_name='Description')),
                ('photo', models.ImageField(upload_to=club.models.capture_photo, verbose_name='Photo')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.season', verbose_name='Season')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Club')),
                ('members', models.IntegerField(blank=True, null=True, verbose_name='Members')),
                ('city', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stad')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('picture', models.ImageField(default='about/default_image.jpg', upload_to=club.models.about_image, verbose_name='Picture')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.season', verbose_name='Season')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('short_description', models.TextField(blank=True, max_length=50, null=True, verbose_name='Short description')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Role')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.season', verbose_name='Season')),
            ],
            options={
                'unique_together': {('season', 'profile')},
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Coach')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.season', verbose_name='Season')),
            ],
            options={
                'unique_together': {('season', 'profile')},
            },
        ),
        migrations.AddConstraint(
            model_name='club',
            constraint=models.UniqueConstraint(fields=('name', 'season'), name='unique_clubname_per_season'),
        ),
    ]
