# Generated by Django 5.1.2 on 2024-10-20 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
        ("club", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="season",
        ),
        migrations.AlterField(
            model_name="coach",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
                verbose_name="Coach",
            ),
        ),
        migrations.AlterField(
            model_name="role",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="accounts.profile",
                verbose_name="Role",
            ),
        ),
    ]
