# Generated by Django 3.2.13 on 2022-11-11 02:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220813_1836'),
        ('club', '0002_coach'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('short_description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Short description')),
                ('profile', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Role')),
            ],
        ),
    ]
