# Generated by Django 5.1.2 on 2024-10-20 15:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0003_delete_subscription"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="description",
        ),
        migrations.RemoveField(
            model_name="photo",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sponsors",
            name="description",
        ),
        migrations.RemoveField(
            model_name="sponsors",
            name="short_description",
        ),
    ]
