# Generated by Django 3.2.13 on 2022-11-11 18:23

import club.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title')),
                ('description', models.TextField(blank=True, max_length=200, null=True, verbose_name='Description')),
                ('short_description', models.TextField(blank=True, max_length=20, null=True, verbose_name='Short description')),
                ('logo', models.ImageField(default='sponsor/default.jpg', upload_to=club.models.sponsor_logo, verbose_name='Logo')),
            ],
        ),
        migrations.AlterField(
            model_name='role',
            name='short_description',
            field=models.TextField(blank=True, max_length=20, null=True, verbose_name='Short description'),
        ),
    ]
