# Generated by Django 3.2.13 on 2022-11-11 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20221111_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.IntegerField(max_length=255, verbose_name='Season'),
        ),
    ]
