# Generated by Django 3.2.13 on 2022-11-12 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_alter_season_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='season',
            name='name',
            field=models.IntegerField(verbose_name='Season'),
        ),
    ]
