# Generated by Django 3.2.13 on 2022-11-12 03:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0006_alter_season_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.season', verbose_name='Season'),
        ),
    ]
