# Generated by Django 3.2.13 on 2022-11-12 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0007_role_season'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='short_description',
            field=models.TextField(blank=True, max_length=50, null=True, verbose_name='Short description'),
        ),
    ]
