# Generated by Django 3.2.13 on 2023-08-20 15:04

import datetime
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Hoofdklasse', 'Hoofdklasse'), ('Overgangsklasse', 'Overgangsklasse'), ('Eerste Klasse', 'Eerste Klasse'), ('Tweede Klasse', 'Tweede Klasse'), ('Derde Klasse', 'Derde Klasse'), ('Vierde Klasse', 'Vierde Klasse')], max_length=50, verbose_name='League')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Team')),
                ('points_earned', models.IntegerField(verbose_name='Earned Points')),
                ('matches_played', models.IntegerField(verbose_name='Played Matches')),
                ('club', models.ForeignKey(blank=True, limit_choices_to={'season__end_date__gte': datetime.date(2023, 8, 20), 'season__start_date__lte': datetime.date(2023, 8, 20)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club', verbose_name='Club')),
                ('coach', models.ForeignKey(blank=True, limit_choices_to={'season__end_date__gte': datetime.date(2023, 8, 20), 'season__start_date__lte': datetime.date(2023, 8, 20)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.coach', verbose_name='Coach')),
                ('league', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='teams.league', verbose_name='League')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('positions', multiselectfield.db.fields.MultiSelectField(choices=[('forward', 'Forward'), ('midfielder', 'Midfielder'), ('defender', 'Defender'), ('goalkeeper', 'Goalkeeper')], max_length=38, verbose_name='Positions')),
                ('number_plate', models.IntegerField(verbose_name='Number plate')),
                ('is_captain', models.BooleanField(blank=True, verbose_name='captain')),
                ('wish', models.TextField(blank=True, max_length=255, null=True, verbose_name='Wish')),
                ('profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.profile', verbose_name='Profile')),
                ('subscription', models.ForeignKey(blank=True, limit_choices_to={'season__end_date__gte': datetime.date(2023, 8, 20), 'season__start_date__lte': datetime.date(2023, 8, 20)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.subscription', verbose_name='Subscription')),
                ('team', models.ForeignKey(blank=True, limit_choices_to={'club__season__end_date__gte': datetime.date(2023, 8, 20), 'club__season__start_date__lte': datetime.date(2023, 8, 20)}, null=True, on_delete=django.db.models.deletion.CASCADE, to='teams.team', verbose_name='Team')),
            ],
        ),
    ]
