# Generated by Django 5.1.2 on 2024-10-20 14:44

import datetime
import django.db.models.deletion
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("club", "0002_remove_subscription_season_alter_coach_profile_and_more"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="subscription",
        ),
        migrations.AlterField(
            model_name="player",
            name="positions",
            field=multiselectfield.db.fields.MultiSelectField(
                choices=[
                    ("middenvelder", "Middenvelder"),
                    ("aanvaller", "Aanvaller"),
                    ("verdediger", "Verdediger"),
                    ("goalkeeper", "Goalkeeper"),
                ],
                max_length=44,
                verbose_name="Positions",
            ),
        ),
        migrations.AlterField(
            model_name="player",
            name="team",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "club__season__end_date__gte": datetime.date(2024, 10, 20),
                    "club__season__start_date__lte": datetime.date(2024, 10, 20),
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="teams.team",
                verbose_name="Team",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="club",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "season__end_date__gte": datetime.date(2024, 10, 20),
                    "season__start_date__lte": datetime.date(2024, 10, 20),
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="club.club",
                verbose_name="Club",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="coach",
            field=models.ForeignKey(
                blank=True,
                limit_choices_to={
                    "season__end_date__gte": datetime.date(2024, 10, 20),
                    "season__start_date__lte": datetime.date(2024, 10, 20),
                },
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="club.coach",
                verbose_name="Coach",
            ),
        ),
    ]
