# Generated by Django 5.1.2 on 2024-10-20 15:29

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("teams", "0002_remove_player_subscription_alter_player_positions_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="player",
            name="wish",
        ),
    ]
