# Generated by Django 3.2.13 on 2022-11-08 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_auto_20220820_0114'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='shortname',
            field=models.CharField(default='1e klasse', max_length=10, verbose_name='League'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='league',
            name='name',
            field=models.CharField(max_length=10, verbose_name='League'),
        ),
    ]
