# Generated by Django 3.2.13 on 2022-11-08 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0004_auto_20221108_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='league',
            name='shortname',
            field=models.CharField(max_length=10, verbose_name='Short League'),
        ),
    ]
