# Generated by Django 3.2.13 on 2022-08-13 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('players', '0002_auto_20220813_1836'),
        ('club', '0002_coach'),
        ('games', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Scores',
            new_name='Goals',
        ),
    ]
