# Generated by Django 5.1.2 on 2024-10-20 14:44

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0001_initial"),
        ("teams", "0002_remove_player_subscription_alter_player_positions_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="game",
            name="away_team",
            field=models.ForeignKey(
                limit_choices_to={
                    "club__season__end_date__gte": datetime.date(2024, 10, 20),
                    "club__season__start_date__lte": datetime.date(2024, 10, 20),
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Away_Team",
                to="teams.team",
                verbose_name="Away",
            ),
        ),
        migrations.AlterField(
            model_name="game",
            name="home_team",
            field=models.ForeignKey(
                limit_choices_to={
                    "club__season__end_date__gte": datetime.date(2024, 10, 20),
                    "club__season__start_date__lte": datetime.date(2024, 10, 20),
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="Home_Team",
                to="teams.team",
                verbose_name="Home",
            ),
        ),
    ]
