# Generated by Django 5.1.2 on 2024-10-20 14:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("games", "0002_alter_game_away_team_alter_game_home_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="score",
            name="assists",
        ),
    ]
