# Generated by Django 3.2.13 on 2022-11-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0004_remove_game_completed'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_day',
            options={'get_latest_by': ['date']},
        ),
    ]
