# Generated by Django 3.2.13 on 2022-11-15 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_photo_title'),
        ('teams', '0007_alter_team_coach'),
        ('games', '0005_auto_20221115_1236'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('leauge_code', 'gameday', 'season')},
        ),
        migrations.AlterUniqueTogether(
            name='match_team',
            unique_together={('team', 'season')},
        ),
    ]
