# Generated by Django 3.2.13 on 2022-11-10 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0005_alter_game_day_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='game_day',
            options={},
        ),
    ]
