# Generated by Django 3.2.13 on 2022-11-15 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_photo_title'),
        ('games', '0006_auto_20221115_1239'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='game',
            unique_together={('leauge_code', 'season')},
        ),
    ]
