# Generated by Django 3.2.13 on 2023-01-24 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0011_alter_photo_title'),
        ('players', '0004_alter_player_profile'),
        ('games', '0007_alter_game_unique_together'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Goals',
            new_name='Score',
        ),
    ]
