# Generated by Django 3.2.13 on 2023-01-24 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0008_rename_goals_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='score',
            name='assists',
            field=models.IntegerField(default='1', verbose_name='assists'),
            preserve_default=False,
        ),
    ]
