# Generated by Django 3.2.25 on 2025-03-01 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('club_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(default=django.utils.timezone.now, max_length=128, verbose_name='Housenumber*'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='place',
            field=models.CharField(default=django.utils.timezone.now, max_length=64, verbose_name='City*'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode',
            field=models.CharField(default='3524', max_length=5, verbose_name='Zipcode Number*'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='address',
            name='zipcode_number',
            field=models.CharField(default='DD', max_length=128, verbose_name='Zipcode Letter*'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=128, verbose_name='Street*'),
        ),
        migrations.AlterField(
            model_name='sponsor',
            name='logo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='sponsors/'),
            preserve_default=False,
        ),
    ]
