# Generated by Django 3.2.13 on 2022-11-11 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_auto_20221111_1923'),
        ('players', '0002_auto_20220813_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='season',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.season', verbose_name='Season'),
        ),
    ]
