# Generated by Django 3.2.25 on 2025-03-01 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('league', models.CharField(choices=[('Hoofdklasse', 'Hoofdklasse'), ('Overgangsklasse', 'Overgangsklasse'), ('Eerste Klasse', 'Eerste Klasse'), ('Tweede Klasse', 'Tweede Klasse'), ('Derde Klasse', 'Derde Klasse'), ('Vierde Klasse', 'Vierde Klasse')], max_length=50, verbose_name='league*')),
                ('league_code', models.CharField(blank=True, max_length=50, null=True)),
                ('field', models.IntegerField(verbose_name='Field*')),
                ('start_time', models.TimeField(verbose_name='start time*')),
                ('end_time', models.TimeField(verbose_name='end time*')),
                ('home_score', models.IntegerField(blank=True, null=True)),
                ('away_score', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.CharField(choices=[('aanvaller', 'Aanvaller'), ('middenvelder', 'Middenvelder'), ('verdediger', 'Verdediger'), ('goalkeeper', 'Goalkeeper')], max_length=50, verbose_name='Position*')),
                ('number_plate', models.PositiveIntegerField(verbose_name='Number_plate*')),
                ('captain', models.BooleanField(default=False)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.profile', verbose_name='Profile*')),
            ],
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Start Date*')),
                ('end_date', models.DateField(verbose_name='End Date*')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date*')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonal.season', verbose_name='Season*')),
                ('training_location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.traininglocation', verbose_name='Training Location*')),
                ('training_time', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.trainingtime', verbose_name='Training Time*')),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name*')),
                ('league', models.CharField(choices=[('Hoofdklasse', 'Hoofdklasse'), ('Overgangsklasse', 'Overgangsklasse'), ('Eerste Klasse', 'Eerste Klasse'), ('Tweede Klasse', 'Tweede Klasse'), ('Derde Klasse', 'Derde Klasse'), ('Vierde Klasse', 'Vierde Klasse')], max_length=50, verbose_name='league*')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club_management.club', verbose_name='Club*')),
                ('coach', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_management.coach')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goals', models.PositiveIntegerField(default=0, verbose_name='Goals*')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonal.game', verbose_name='Game*')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasonal.player', verbose_name='Player*')),
            ],
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonal.team', verbose_name='Team*'),
        ),
        migrations.CreateModel(
            name='Game_day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sport_hall', models.CharField(max_length=100, verbose_name='Sporthal*')),
                ('date', models.DateField(verbose_name='Date*')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='club_management.address')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonal.season', verbose_name='Season*')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='away_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Away_Team', to='seasonal.team', verbose_name='Away Team*'),
        ),
        migrations.AddField(
            model_name='game',
            name='gameday',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='seasonal.game_day', verbose_name='Game Day*'),
        ),
        migrations.AddField(
            model_name='game',
            name='home_team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Home_Team', to='seasonal.team', verbose_name='Home Team*'),
        ),
    ]
