# Generated by Django 3.2.25 on 2025-03-01 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='field',
            field=models.PositiveIntegerField(verbose_name='Field*'),
        ),
    ]
