# Generated by Django 3.2.25 on 2025-03-01 18:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal', '0002_alter_game_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=15, verbose_name='Title -> 1x naam perdag, Verander naam hier != als file naam')),
                ('photo', models.ImageField(upload_to='photo/', verbose_name='Photo')),
                ('season', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='seasonal.season', verbose_name='Season')),
            ],
        ),
    ]
