# Generated by Django 3.2.25 on 2025-03-01 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seasonal', '0003_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='season',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='seasonal.season', verbose_name='Season*'),
            preserve_default=False,
        ),
    ]
